# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: info@datawars.io
author_name: datawars.io
data_format: string
file_extension: ''
has_binder: false
has_settings: true
kind: frontend
labextension_name: jupyterlab-notebook-messages
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension that will messages your open Notebook.
python_name: jupyterlab_notebook_messages
repository: https://github.com/datawars-io/jupyterlab-notebook-messages
test: false
viewer_name: ''

